### PR TITLE
Fix bugs, make it easier to debug errors, and allow ERB in YAML file

### PR DESCRIPTION
**Pull request by wmakley**
Just tried to use this and fixed some issues I came across. Hopefully this helps! I didn't bump the gem version, but getting a new version on rubygems would be awesome.
- ERB in YAML so I could put the API key in an environment variable. Need to be able to commit the config file, but not the secrets.
- The script had a bug, but I couldn't fix it because it was eating the stacktrace, so I added stacktrace printing with verbose on. It might be better just to re-raise the exception though. I think the only exceptions you really want to catch and inform the user about would have to do with mis-configuring the contentful YAML file. Everything else is a bug in c2h.

### CODE REVIEW

**Comment by roundedbygravity** [comment]
@ArnoNuyts is there a reason this isn't merged? Seems good.

**Comment by wmakley** [comment]
I may have screwed up. If I am reading it correctly, apparently the pull request now contains all my experimental changes, not just the commit when I created the pull request. I am confused.

**Comment by Camzilla** [comment]
You might wanna revert the commit about making the config default extension "yml" and not "yaml". Either that or properly update the readme file :)

**Comment by wmakley** [comment]
Sorry, I fixed it. This is not something I am using heavily, as what I really need with hugo is an asset pipeline, and that is not Ruby's forté.

**Pull request merged**
